[[redirects]]
  from = "/infographics"
  to = "/slidesets"
  status = 301

[[redirects]]
  from = "/pride-month-2022/"
  to = "/pride-month/2022/"
  status = 301

[[redirects]]
  from = "/pride-month/"
  to = "/pride-month/2022/"
  status = 301

[[redirects]]
  from = "/pride-month/articles/"
  to = "/pride-month/2022/"
  status = 301

[dev]
  autoLaunch = false
  port = 30

# For shortened URLs:
[[redirects]]
  from = "/infographics-download"
  to = "https://github.com/antaresphdev/infographics"
  status = 301
  force = true
  headers = {X-From = "Netlify"}